# Generated by Django 5.1.5 on 2025-04-21 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "assessments",
            "0003_alter_assessment_options_alter_giftprofile_options_and_more",
        ),
        ("counselors", "__first__"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="counselor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conducted_assessments",
                to="counselors.counselor",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="counselor_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="assessment",
            name="is_counselor_session",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assessment",
            name="session_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
