# Generated by Django 5.2.1 on 2025-05-17 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('associated_gift', models.CharField(choices=[('PERCEPTION', 'Perception (Prophecy)'), ('SERVICE', 'Service'), ('TEACHING', 'Teaching'), ('EXHORTATION', 'Exhortation'), ('GIVING', 'Giving'), ('ADMINISTRATION', 'Administration'), ('COMPASSION', 'Compassion')], help_text='The motivational gift this book corresponds to', max_length=20)),
                ('slug', models.SlugField(unique=True)),
                ('publication_info', models.JSONField(default=dict, help_text='Publication details including publisher, year, etc.')),
                ('copyright_info', models.TextField()),
                ('version', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CareerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(help_text='Order in which category appears in book')),
                ('slug', models.SlugField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='books.book')),
            ],
            options={
                'verbose_name_plural': 'Career Categories',
                'ordering': ['order'],
                'unique_together': {('book', 'order'), ('book', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('possibility_rating', models.CharField(choices=[('HP', 'Highly Possible'), ('VP', 'Very Possible'), ('P', 'Possible')], max_length=2)),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='books.career')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='books.careercategory')),
            ],
            options={
                'verbose_name_plural': 'Careers',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CareerChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_notes', models.TextField(blank=True, help_text='Additional notes about career choices and research plans')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_final', models.BooleanField(default=False, help_text="Indicates if this is the user's final career goal selection")),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_career_choices', to='books.book')),
                ('career_choice_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_choices', to='books.career')),
                ('career_choice_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_choices', to='books.career')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_choices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Career Choice',
                'verbose_name_plural': 'Career Choices',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'book')},
            },
        ),
        migrations.CreateModel(
            name='CareerResearchNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('RESEARCH', 'Research Note'), ('QUESTION', 'Question to Ask'), ('REQUIREMENT', 'Career Requirement'), ('GOAL', 'Career Goal'), ('OTHER', 'Other Note')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_notes', to='books.careerchoice')),
            ],
            options={
                'verbose_name': 'Career Research Note',
                'verbose_name_plural': 'Career Research Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('access_reason', models.CharField(choices=[('PRIMARY', 'Primary Gift'), ('SECONDARY', 'Secondary Gift'), ('PURCHASED', 'Purchased Access')], max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Book Access',
                'unique_together': {('user', 'book')},
            },
        ),
        migrations.CreateModel(
            name='CareerBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='books.career')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'career')},
            },
        ),
        migrations.CreateModel(
            name='ReadingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('last_position', models.PositiveIntegerField(default=0, help_text='Last read position in category')),
                ('read_duration', models.DurationField(blank=True, help_text='Total time spent reading this category', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_history', to='books.careercategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reading Histories',
                'unique_together': {('user', 'category')},
            },
        ),
        migrations.CreateModel(
            name='UserBookProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='books.book')),
                ('current_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_users', to='books.careercategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'book')},
            },
        ),
    ]
