# Generated by Django 5.1.4 on 2025-01-13 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='associated_gift',
            field=models.CharField(choices=[('PERCEPTION', 'Perception (Prophecy)'), ('SERVICE', 'Service'), ('TEACHING', 'Teaching'), ('EXHORTATION', 'Exhortation'), ('GIVING', 'Giving'), ('ADMINISTRATION', 'Administration'), ('COMPASSION', 'Compassion')], help_text='The motivational gift this book corresponds to', max_length=20),
        ),
        migrations.CreateModel(
            name='CareerChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_notes', models.TextField(blank=True, help_text='Additional notes about career choices and research plans')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_final', models.BooleanField(default=False, help_text="Indicates if this is the user's final career goal selection")),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_career_choices', to='books.book')),
                ('career_choice_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_choices', to='books.career')),
                ('career_choice_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_choices', to='books.career')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_choices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Career Choice',
                'verbose_name_plural': 'Career Choices',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'book')},
            },
        ),
        migrations.CreateModel(
            name='CareerResearchNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('RESEARCH', 'Research Note'), ('QUESTION', 'Question to Ask'), ('REQUIREMENT', 'Career Requirement'), ('GOAL', 'Career Goal'), ('OTHER', 'Other Note')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_notes', to='books.careerchoice')),
            ],
            options={
                'verbose_name': 'Career Research Note',
                'verbose_name_plural': 'Career Research Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
