# Generated by Django 5.1.4 on 2025-01-13 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_associated_gift_careerchoice_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='career',
            unique_together=set(),
        ),
    ]
